name: Netlify CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]     

jobs:
  runCI:
    name: Run CI with Postgres
    runs-on: ubuntu-latest
    steps:
      - name: Set up Postgres
        uses: CasperWA/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'test'

      - name: Set project directory
        id: project-directory
        run: echo "::set-output name=dir::./netlify"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Project is using Yarn 3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      
      - name: Install dependencies
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn install --immutable
        
      - name: Run Build
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw build

      # missing a service implementation 
      # - name: Run Diagnostics
      #   working-directory: ${{ steps.project-directory.outputs.dir }}
      #   run: yarn rw check
        
      - name: Run Tests
        working-directory: ${{ steps.project-directory.outputs.dir }}
        run: yarn rw test
        env:
          TEST_DATABASE_URL: postgresql://postgres@localhost:5432/test